### ISSUE TITLE
Setting up/installing POV-ray on the remote server

### ISSUE THREAD

**Issue by posfan12** [awslabs/lambda-ecs-worker-pattern#4]
I was reading the Better Together: Amazon ECS and AWS Lambda blog post.

https://aws.amazon.com/blogs/compute/better-together-amazon-ecs-and-aws-lambda/

However, I could not find instructions on how to install POV-Ray on the remote server. Do we need to set that up, as well as the operating system? Or are they already configured?

Also, do you get charged for the CPU time spent while setting up and configuring the operating system and software?

Thanks.

**Comment by glez-aws** [comment]
Hi posfan12,

thanks for checking out our blog post.

Everything necessary to set this up is included in the fabfile in this repository, including a Dockerfile that will set up POV-Ray inside a Docker container.

Yes, running a Docker container on Amazon ECS requires a running ECS cluster which means you will need to set up at least one EC2 instance to run your ECS cluster on. For the time that the cluster is running, you will be billed the standard EC2 charges.

You may be able to take advantage of the AWS free tier: http://aws.amazon.com/free.

Thanks,
   Constantin

**Comment by glez-aws** [comment]
Closing this issue, hoping the above answer is enough. Otherwise feel free to reopen.
