### ISSUE TITLE
undo all steps in the fabfile

### ISSUE THREAD

**Issue by koppi** [awslabs/lambda-ecs-worker-pattern#5]
Can you please add a function to fabfile.py that un-does all the steps that were done in the setup function? Something like `fab setup` / `fab unsetup` would be helpful.

**Comment by chumanfu** [comment]
I have been unable to use this script without uncommenting the "docker login" line. Am I doing something wrong or is the script wrong?

**Comment by glez-aws** [comment]
Hi koppi,

thanks for your comment and feature request. Unfortunately, I'm very busy right now, so implementing this may take some time, but it’s definitely on my list now.

Thanks,
   Constantin

**Comment by glez-aws** [comment]
Hi chumanfu,

thanks for your comment.

The original version of this script used Dockerhub to host the images. In this case, the (now commented) docker line is the right mechanism to use.

Then, a feature request was accepted that added support for Amazon EC2 Container Repository (ECR), which uses a different authentication mechanism (the aws ecr get-login line).

If you want to use Dockerhub, then, yes, you should uncomment the docker login line and comment out the three (3) login_str lines, including the aws ecr get-login line and you should be good to go.

If you want to use Amazon ECR for storing your Docker images, then the script should work as is and you would need to set up your Amazon ECR repository first, before using this script.

Hope this helps,
   Constantin
